### ISSUE TITLE
after I buildout, I'm getting error: ImportError: No module named ATContentTypes.lib.imagetransform

### ISSUE THREAD

**Issue by 3dtechart** [collective/collective.embedcontent#10]
Hello,

after I did buildout with collective.embedcontent in plone 5.2, I'm getting error: ImportError: No module named ATContentTypes.lib.imagetransform
please take a look at this.

thanks,
-Jun

**Comment by djay** [comment]
@3dtechart can you provide the full stacktrace and the steps to reproduce end to end?

**Comment by 3dtechart** [comment]
Here is what I did. thanks for reply so quickly.

[junghunkim@wf-103-44-220-89 zinstance]$ ./bin/buildout
Uninstalling zopepy.
Uninstalling instance.
Installing instance.
Generated script '/home/junghunkim/webapps/techart/zinstance/bin/instance'.
Generated interpreter '/home/junghunkim/webapps/techart/zinstance/parts/instance/bin/interpreter'.
Generated script '/home/junghunkim/webapps/techart/zinstance/bin/update_locale'.
Updating repozo.
Updating backup.
Installing zopepy.
Generated interpreter '/home/junghunkim/webapps/techart/zinstance/bin/zopepy'.
Updating unifiedinstaller.
Versions had to be automatically picked.
The following part definition lists the versions picked:
[versions]
collective.embedcontent = 1.0a1
[junghunkim@wf-103-44-220-89 zinstance]$ ./bin/plonectl fg
instance: /home/junghunkim/webapps/techart/buildout-cache/eggs/Products.Archetypes-1.16.1-py2.7.egg/Products/Archetypes/generator/widget.py:4: DeprecationWarning: InitializeClass is deprecated. Please import from AccessControl.class_init.
  from App.class_init import InitializeClass
/home/junghunkim/webapps/techart/buildout-cache/eggs/Products.ZSQLMethods-3.0.9-py2.7.egg/Shared/DC/ZRDB/DA.py:61: DeprecationWarning: ResourceLockedError is deprecated. Please import from zExceptions.
  from webdav.Lockable import ResourceLockedError
/home/junghunkim/webapps/techart/buildout-cache/eggs/Products.Archetypes-1.16.1-py2.7.egg/Products/Archetypes/interfaces/event.py:4: DeprecationWarning: IObjectEvent is deprecated. Import from zope.interface.interfaces
  from zope.component.interfaces import IObjectEvent
/home/junghunkim/webapps/techart/buildout-cache/eggs/Products.Archetypes-1.16.1-py2.7.egg/Products/Archetypes/ReferenceEngine.py:31: DeprecationWarning: LazyMap is deprecated. Please import from ZTUtils.Lazy.
  from Products.ZCatalog.Lazy import LazyMap
/home/junghunkim/webapps/techart/buildout-cache/eggs/plone.app.imaging-2.1.1-py2.7.egg/plone/app/imaging/__init__.py:2: DeprecationWarning: setDefaultRoles is deprecated. Please use addPermission from AccessControl.Permission.
  from Products.CMFCore.permissions import setDefaultRoles
/home/junghunkim/webapps/techart/buildout-cache/eggs/Products.Archetypes-1.16.1-py2.7.egg/Products/Archetypes/event.py:6: DeprecationWarning: ObjectEvent is deprecated. Import from zope.interface.interfaces
  from zope.component.interfaces import ObjectEvent
/home/junghunkim/webapps/techart/buildout-cache/eggs/Products.GenericSetup-2.0.1-py2.7.egg/Products/GenericSetup/registry.py:16: ImportWarning: Not importing directory '/home/junghunkim/webapps/techart/buildout-cache/eggs/Products.GenericSetup-2.0.1-py2.7.egg/Products/GenericSetup/xml': missing __init__.py
  from xml.sax import parseString
2020-07-08 04:44:51,470 WARNING [Init:89][MainThread] Class Products.CMFFormController.ControllerPythonScript.ControllerPythonScript has a security declaration for nonexistent method 'ZPythonScriptHTML_changePrefs'
2020-07-08 04:44:51,483 WARNING [Init:89][MainThread] Class Products.CMFFormController.ControllerValidator.ControllerValidator has a security declaration for nonexistent method 'ZPythonScriptHTML_changePrefs'
2020-07-08 04:44:52,229 WARNING [TemporaryStorage:93][MainThread] DEPRECATED: Usage of the package tempstorage is deprecated, as it is known to randomly lose data.
Especially on Zope 4. For details see https://github.com/zopefoundation/tempstorage/issues/8
and https://github.com/zopefoundation/tempstorage

/home/junghunkim/webapps/techart/buildout-cache/eggs/tempstorage-5.1-py2.7.egg/tempstorage/TemporaryStorage.py:94: DeprecationWarning: DEPRECATED: Usage of the package tempstorage is deprecated, as it is known to randomly lose data.
Especially on Zope 4. For details see https://github.com/zopefoundation/tempstorage/issues/8
and https://github.com/zopefoundation/tempstorage

  warnings.warn(deprecation_warning, DeprecationWarning)
/home/junghunkim/webapps/techart/buildout-cache/eggs/plone.app.upgrade-2.0.31-py2.7.egg/plone/app/upgrade/__init__.py:155: DeprecationWarning: GopipIndex is deprecated. Please import from plone.folder.nogopip
  from plone.app.folder.nogopip import GopipIndex
/home/junghunkim/webapps/techart/buildout-cache/eggs/plone.app.upgrade-2.0.31-py2.7.egg/plone/app/upgrade/__init__.py:167: DeprecationWarning: LockItem is deprecated. Please import from OFS.LockItem.
  from webdav.LockItem import LockItem
/home/junghunkim/webapps/techart/buildout-cache/eggs/plone.subrequest-1.9.1-py2.7.egg/plone/subrequest/__init__.py:18: DeprecationWarning: zope.site.hooks has moved to zope.component.hooks. Import of zope.site.hooks will become unsupported in Version 5.0
  from zope.site.hooks import getSite
/home/junghunkim/webapps/techart/buildout-cache/eggs/Products.Archetypes-1.16.1-py2.7.egg/Products/Archetypes/mimetype_utils.py:9: DeprecationWarning: ComponentLookupError is deprecated. Import from zope.interface.interfaces
  from zope.component.interfaces import ComponentLookupError
/home/junghunkim/webapps/techart/buildout-cache/eggs/plone.app.content-3.7.4-py2.7.egg/plone/app/content/browser/vocabulary.py:10: DeprecationWarning: IFieldPermissionChecker is deprecated. Import IFieldPermissionChecker from plone.app.z3cform.interfaces instead
  from plone.app.widgets.interfaces import IFieldPermissionChecker
/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py:240: DeprecationWarning: IComponentRegistry is deprecated. Import from zope.interface.interfaces
  obj = getattr(mod, oname)
Traceback (most recent call last):
  File "/home/junghunkim/webapps/techart/zinstance/parts/instance/bin/interpreter", line 300, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/Zope-4.1.3-py2.7.egg/Zope2/Startup/serve.py", line 255, in <module>
    sys.exit(main() or 0)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/Zope-4.1.3-py2.7.egg/Zope2/Startup/serve.py", line 251, in main
    return command.run()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/Zope-4.1.3-py2.7.egg/Zope2/Startup/serve.py", line 190, in run
    global_conf=vars)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/Zope-4.1.3-py2.7.egg/Zope2/Startup/serve.py", line 220, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/PasteDeploy-2.0.1-py2.7.egg/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/PasteDeploy-2.0.1-py2.7.egg/paste/deploy/loadwsgi.py", line 278, in loadobj
    return context.create()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/PasteDeploy-2.0.1-py2.7.egg/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/PasteDeploy-2.0.1-py2.7.egg/paste/deploy/loadwsgi.py", line 209, in invoke
    app = context.app_context.create()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/PasteDeploy-2.0.1-py2.7.egg/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/PasteDeploy-2.0.1-py2.7.egg/paste/deploy/loadwsgi.py", line 152, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/PasteDeploy-2.0.1-py2.7.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/Zope-4.1.3-py2.7.egg/Zope2/Startup/run.py", line 71, in make_wsgi_app
    starter.prepare()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/Zope-4.1.3-py2.7.egg/Zope2/Startup/starter.py", line 41, in prepare
    self.startZope()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/Zope-4.1.3-py2.7.egg/Zope2/Startup/starter.py", line 98, in startZope
    Zope2.startup_wsgi()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/Zope-4.1.3-py2.7.egg/Zope2/__init__.py", line 50, in startup_wsgi
    _startup()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/Zope-4.1.3-py2.7.egg/Zope2/App/startup.py", line 143, in startup
    load_zcml()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/Zope-4.1.3-py2.7.egg/Zope2/App/startup.py", line 58, in load_zcml
    load_site()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/Zope-4.1.3-py2.7.egg/Zope2/App/zcml.py", line 45, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 657, in file
    include(context, name, package)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 868, in finish
    actions = self.handler(context, **args)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/Zope-4.1.3-py2.7.egg/OFS/metaconfigure.py", line 47, in loadProducts
    xmlconfig.include(_context, zcml, package=product)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 868, in finish
    actions = self.handler(context, **args)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 868, in finish
    actions = self.handler(context, **args)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 868, in finish
    actions = self.handler(context, **args)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 868, in finish
    actions = self.handler(context, **args)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/home/junghunkim/webapps/techart/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 235, in _handle_exception
    reraise(exc, None, sys.exc_info()[2])
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 867, in finish
    args = toargs(context, *self.argdata)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 1686, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/fields.py", line 268, in fromUnicode
    v = vt.fromUnicode(s)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/fields.py", line 171, in fromUnicode
    value = self.context.resolve(name)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 225, in resolve
    __import__(mname)
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/plone.protect-4.1.3-py2.7.egg/plone/protect/auto.py", line 51, in <module>
    from plone.app.blob.content import ATBlob
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/plone.app.blob-1.8.0-py2.7.egg/plone/app/blob/content.py", line 6, in <module>
    from plone.app.blob.field import BlobMarshaller
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/plone.app.blob-1.8.0-py2.7.egg/plone/app/blob/field.py", line 18, in <module>
    from plone.app.blob.mixins import ImageFieldMixin
  File "/home/junghunkim/webapps/techart/buildout-cache/eggs/plone.app.blob-1.8.0-py2.7.egg/plone/app/blob/mixins.py", line 7, in <module>
    from Products.ATContentTypes.lib.imagetransform import ATCTImageTransform
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/home/junghunkim/webapps/techart/buildout-cache/eggs/plone.protect-4.1.3-py2.7.egg/plone/protect/configure.zcml", line 32.4-35.10
    File "/home/junghunkim/webapps/techart/zinstance/parts/instance/etc/site.zcml", line 16.2-16.23
    File "/home/junghunkim/webapps/techart/buildout-cache/eggs/Products.CMFPlone-5.2.1-py2.7.egg/Products/CMFPlone/configure.zcml", line 14.2-14.46
    File "/home/junghunkim/webapps/techart/buildout-cache/eggs/plone.app.contenttypes-2.1.5-py2.7.egg/plone/app/contenttypes/configure.zcml", line 20.2-20.43
    File "/home/junghunkim/webapps/techart/buildout-cache/eggs/plone.app.dexterity-2.6.4-py2.7.egg/plone/app/dexterity/configure.zcml", line 15.2-15.42
    File "/home/junghunkim/webapps/techart/buildout-cache/eggs/plone.schemaeditor-2.1.0-py2.7.egg/plone/schemaeditor/configure.zcml", line 8.2-8.36
    ImportError: No module named ATContentTypes.lib.imagetransform

**Comment by djay** [comment]
Seems that the person who wrote it used an older deprecated api (plone.app.blob) instead of plone.namedfile.

**Comment by djay** [comment]
Need to 
- switch for namedfile. 
- at the same time it looks like dict is being used instead of oobtrees which can cause problems for large zips so that needs to be switched
- put in a upgrade profile to update existing instances
